version:  '3.8'

services:      
  mysql:
    image: mysql:latest
    volumes:
      - './:/db-data'
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_kiloupabocou
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build:
      context: .
    volumes:
      - './:/app'
      - './:/php/logs'
    ports:
      - '8081:8081'
    restart: on-failure
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - './:/domainname'
      - './:/nginx/logs'
    ports:
      - '8080:80'
    depends_on:
      - php